import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
// import "./style/about.css";
// import "./style/contact.css";
// import "./style/footer.css";
// import "./style/header.css";
// import "./style/home.css";
// import "./style/project.css";
// import "./style/service.css";
// import "./style/testimonial.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={geistSans.className}>
        {children}
      </body>
    </html>
  );
}
