import type { Metadata } from "next";
import { Geist, Geist_Mono, Rowdies } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rowdies = Rowdies({
  subsets: ['latin'], // Gunakan subset latin untuk mendukung karakter bahasa Inggris.
  weight: ['300', '400', '700'], // Tentukan berat font yang dibutuhkan.
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={geistSans.className}>
        {children}
      </body>
    </html>
  );
}
